### PR TITLE
Update QSV refs

### PR DESCRIPTION
**Pull request by avdata99**
After #160 and more changes I think we need to point QSV to 0.134

### CODE REVIEW

**Comment by tino097** [comment]
hey @avdata99 i have created a debian repository for [QSV](https://github.com/tino097/qsv-deb-releases)
would you like to give it a try  ?

**Comment by avdata99** [comment]
Thanks @tino097, I'm testing 1.0.2 with QSV 0.134 now.
I'm using it from the repo https://github.com/jqnatividad/qsv
Do you think we need to change it?

**Comment by tino097** [comment]
@avdata99 no, i meant for nicer way to install QSV to the system, just using `sudo apt install qsv`

**Review by tino097 — APPROVED** [review]

**Comment by avdata99** [comment]
Now I get it @tino097 
It's incredibly slow to build QSV. I'm now in a second project over the CKAN 2.10.5 image (Alpine 3.17) which includes rust 1.64.
So I need to move to rust 1.81 and the build from source.
Do you have any suggestion for this use case?

**Comment by tino097** [comment]
@avdata99 sorry, still haven't done anything about alpine 
we are switching to `ubuntu` slim images instead

**Pull request merged**
